### PR TITLE
Handle truncating file names when they get too long

### PR DESCRIPTION
**Pull request by mattchrlw**

### CODE REVIEW

**Review by nicklambourne — CHANGES_REQUESTED** [review]
Is this missing a commit or something? I've double and triple-checked, and rebuilt the UI, but I'm still getting this (and no tooltip):

Screen Shot 2021-03-22 at 10 30 16 pm

**Comment by mattchrlw** [comment]
Did you double check to run `npm install && npm run watch`?

**Comment by mattchrlw** [comment]
You might also need to Cmd+Shift+R.

**Comment by nicklambourne** [comment]
lol, even more banal, I stumbled on a bug in the oh-my-zsh git plugin

**Review by nicklambourne — APPROVED** [review]
LGTM, disregard previous review

**Pull request merged**
